language: csharp
mono: none
dotnet: 3.0
env: DOTNETCORE=3.0
solution: Nexmo.Api.sln
script:  
  - dotnet test ./Nexmo.Api.Test.Unit/Nexmo.Api.Test.Unit.csproj -f netcoreapp3.0
  - curl https://dotnet.microsoft.com/download/dotnet-core/scripts/v1/dotnet-install.sh -o dotnet-install.sh
  - chmod 777 dotnet-install.sh
  - ./dotnet-install.sh --channel 3.0
  - ./dotnet-install.sh --channel 2.2
  - ./dotnet-install.sh --channel 2.1
  - ./dotnet-install.sh --channel 2.0
  - ~/.dotnet/dotnet test ./Nexmo.Api.Test.Unit/Nexmo.Api.Test.Unit.csproj -f netcoreapp2.2
  - ~/.dotnet/dotnet test ./Nexmo.Api.Test.Unit/Nexmo.Api.Test.Unit.csproj -f netcoreapp2.1
  - sudo apt install libunwind8
  - ~/.dotnet/dotnet test ./Nexmo.Api.Test.Unit/Nexmo.Api.Test.Unit.csproj -f netcoreapp2.0